name: KitUI
main: KienDev\Kit\Main
api: 5.0.0
version: 0.0.1
author:
- KienDev
description: Plugin KitUI Code By KienDev
permissions:
  kit.menu:
    default: true
  kit.give:
    default: op
  kit.create:
    default: op
  kit.manage:
    default: op
