#
# ██╗  ██╗██╗███████╗███╗   ██╗██████╗ ███████╗██╗   ██╗
# ██║ ██╔╝██║██╔════╝████╗  ██║██╔══██╗██╔════╝██║   ██║
# █████╔╝ ██║█████╗  ██╔██╗ ██║██║  ██║█████╗  ██║   ██║
# ██╔═██╗ ██║██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ╚██╗ ██╔╝
# ██║  ██╗██║███████╗██║ ╚████║██████╔╝███████╗ ╚████╔╝ 
# ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝  ╚═══╝  
#          Copyright © 2024 - 2025 KienDev 

economy:
   provider: economyapi
#Get Type Of The Economy

kits:
  - name: "Kit Member"
    info: "Kit For New Member"
    permission: "memberkit.perm"
    money: 1000
    coin: 10
    items: []
    used-by: ""
